import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useGetAllPodcastsQuery } from '@/store/services/podcastApi'
import Podcast from '@/components/Podcast'

const Home = () => {

  const { data, isLoading } = useGetAllPodcastsQuery();

  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Podcaster</h1>
        {
          isLoading 
            ?
              <p>Loading ...</p>
            :
            <ul>
              {
                data 
                ? 
                data.map((podcast) => <Podcast key={podcast.id.attributes['im:id']} podcast={podcast} />)
                : <p>No data to be displayed</p>
              }
            </ul>
          }
      </main>
    </>
  )
}

export default Home;
